### ISSUE TITLE
What do you mean by "run this for your project" for the LSP? 

### ISSUE THREAD

**Issue by NoamEfergan** [wojciech-kulik/ios-dev-starter-nvim#4]
not sure i understand. 
i just keep getting this: 
` Requested but did not find extension point with identifier`

**Comment by wojciech-kulik** [comment]
I'm not sure what you're referring to.

**Comment by NoamEfergan** [comment]
<img width="879" alt="image" src="https://github.com/wojciech-kulik/ios-dev-starter-nvim/assets/135020606/f7bcd330-0b54-4aee-9dfb-903f63a1f8d9">

**Comment by wojciech-kulik** [comment]
To use it :) https://github.com/SolaWing/xcode-build-server#usage

**Comment by NoamEfergan** [comment]
yeah that's what i assumed hahaha 
so it's failing for me, but that's not a "you" thing, it's a them thing. 
Keep up the good work this is incredible and (when i get it to work lol) i'd love to use it! this has pushed me to learn vim and neovim and put Xcode in vim mode

**Comment by wojciech-kulik** [comment]
Great to hear! Good luck with your adventure, it's worth it! SolaWing is quite helpful with `xcode-build-server`, so If you open a bug, he should be able to help you :)
